trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  pipelines:
  - pipeline: CI
    source: Nerdbank.GitVersioning
    trigger:
      tags:
      - auto-release

stages:
- stage: GitHubRelease
  displayName: GitHub Release
  jobs:
  - deployment: create
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval # Approval is already granted in the release stage.
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - powershell: |
              Write-Host "##vso[build.updatebuildnumber]$(resources.pipeline.CI.runName)"
            displayName: Set pipeline name
          - task: GitHubRelease@1
            displayName: GitHub release (create)
            inputs:
              gitHubConnection: github.com_AArnott_OAuth
              repositoryName: $(Build.Repository.Name)
              target: $(resources.pipeline.CI.sourceCommit)
              tagSource: userSpecifiedTag
              tag: v$(resources.pipeline.CI.runName)
              title: v$(resources.pipeline.CI.runName)
              isDraft: true
              changeLogCompareToRelease: lastNonDraftRelease
              changeLogType: issueBased
              changeLogLabels: |
                [
                  { "label" : "breaking changes", "displayName" : "Breaking changes", "state" : "closed" },
                  { "label" : "bug", "displayName" : "Fixes", "state" : "closed" },
                  { "label" : "enhancement", "displayName": "Enhancements", "state" : "closed" }
                ]

- stage: nuget_org
  displayName: nuget.org
  dependsOn: GitHubRelease
  jobs:
  - deployment: push
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval # Approval is already granted in the release stage.
    strategy:
      runOnce:
        deploy:
          steps:
          - download: CI
            artifact: deployables
            displayName: Download deployables artifact
            patterns: '**/*.*nupkg'
          - task: NuGetToolInstaller@1
            displayName: Use NuGet 5.x
            inputs:
              versionSpec: 5.x
          - task: NuGetCommand@2
            displayName: NuGet push
            inputs:
              command: push
              packagesToPush: $(Pipeline.Workspace)/CI/deployables/*.nupkg
              nuGetFeedType: external
              publishFeedCredentials: nuget.org

- stage: npmjs_org
  displayName: npmjs.org
  dependsOn: GitHubRelease
  jobs:
  - deployment: push
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval # Approval is already granted in the release stage.
    strategy:
      runOnce:
        deploy:
          steps:
          - download: CI
            artifact: deployables
            displayName: Download deployables artifact
            patterns: '**/*.tgz'
          - powershell: |
              $tgz = (Get-ChildItem "$(Pipeline.Workspace)/CI/deployables/*.tgz")[0].FullName

              npm init -y
              npm install $tgz
            workingDirectory: $(Agent.TempDirectory)
            displayName: Prepare to publish NPM package
          - task: Npm@1
            displayName: npm publish
            inputs:
              command: publish
              workingDir: $(Agent.TempDirectory)/node_modules/nerdbank-gitversioning
              verbose: false
              publishEndpoint: npmjs.org
